---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  selector:
    app: grafana
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - env:
        - name: GF_INSTALL_PLUGINS
          value: grafana-piechart-panel, blackmirror1-singlestat-math-panel
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: kraken
        image: grafana/grafana:5.4.3
        name: grafana
        volumeMounts:
        - mountPath: /etc/grafana/provisioning
          name: grafana-volume
          subPath: provisioning/
        - mountPath: /var/lib/grafana/dashboards
          name: grafana-volume
          subPath: dashboards/
        - mountPath: /etc/grafana/grafana.ini
          name: grafana-volume
          subPath: grafana.ini
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: grafana-volume
        hostPath:
          path: /grafana
---
apiVersion: 1

spec:
- name: Analysis Server
  orgId: 1
  type: influxdb
  access: proxy
  url: http://influxdb-service:8086
  database: telegraf
  isDefault: false
  version: 1
  editable: false
  basicAuth: true
  basicAuthUser: admin
  basicAuthPassword: kraken
- name: Gatling
  orgId: 1
  type: influxdb
  access: proxy
  url: http://influxdb-service:8086
  database: gatling
  isDefault: true
  version: 1
  editable: false
  basicAuth: true
  basicAuthUser: user
  basicAuthPassword: kraken
---
apiVersion: 1

providers:
- name: 'dashboards'
  orgId: 1
  folder: ''
  type: file
  disableDeletion: true
  updateIntervalSeconds: 10 #how often Grafana will scan for changed dashboards
  options:
    path: /var/lib/grafana/dashboards
