FROM alpine:latest

WORKDIR /app
VOLUME /app

#RUN chmod 777 /startup.h

COPY startup.sh /startup.sh
RUN chmod +x /startup.sh

RUN apk add --update mysql mysql-client && rm -f /var/cache/apk/*
COPY my.cnf /etc/mysql/my.cnf

EXPOSE 3306
ENTRYPOINT ["/startup.sh"]
