from alpine:latest

RUN apk update && \
	apk add mysql mysql-client && \
	addgroup mysql mysql && \
	rm -rf /var/cache/apk/*

COPY /start.sh /start.sh
COPY my.cnf /etc/mysql/my.cnf

RUN chmod 777 /start.sh

VOLUME ["/var/lib/mysql"]

EXPOSE 3306

ENTRYPOINT ["sh", "/start.sh"]
