#from alpine:latest

#RUN apk add mariadb mariadb-client

#RUN DB_DATA_PATH="/var/lib/mysql"
#RUN DB_ROOT_PASS="mariadb_root_password"
#RUN DB_USER="mariadb_user"
#RUN DB_PASS="mariadb_user_password"
#RUN MAX_ALLOWED_PACKET="200M"

#RUN mysql_install_db --user=mysql --datadir="/var/lib/mysql"

#RUN mariadb start
#RUN mysqladmin -u root password "${DB_ROOT_PASS}"
