apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: ft_services
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: ft_services
    tier: mysql
  clusterIP: None
  externalName: mysql.default

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: ft_services
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: my-mariadb
  labels:
    app: mariadb
    type: database
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
        type: database
    spec:
      containers:
        - name: mariadb
          image: mariadb:latest
          ports:
            - containerPort: 3306
              name: db-port
              hostPort: 80
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: my-password
#          volumeMounts:
#            - name: mysql-persistent-storage
#              mountPath: /app/mysql
#    volumes:
#     - name: mysql-persistent-storage
#       persistentVolumeClaim:
#       claimName: mysql-pv-claim
