from alpine:latest

RUN apk update
RUN apk upgrade
RUN apk add nginx
RUN apk add vim
RUN apk add openssl

# add user
RUN adduser -D -g 'www' www
RUN mkdir /www
RUN chown -R www:www /var/lib/nginx
RUN chown -R www:www /www

RUN mkdir -p /run/nginx

#	backup nginx conf
# RUN mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.orig
RUN rm /etc/nginx/nginx.conf

COPY ./nginx.conf /etc/nginx/
RUN ls /etc/nginx/
RUN cat /etc/nginx/nginx.conf
COPY ./index.html /www/index.html

# test for errors
# CMD rc-service nginx restart
RUN nginx -t

EXPOSE 80

# pour faire tourner en fond
CMD ["nginx", "-g", "daemon off;"]
